[Enhance] Add "Extraction Types" To 2-fa Util Script
* Update 2-fa script to use "extraction types"
* Add support for "line" extraction type, in addition to existing
  "pattern" extraction type

diff --git a/utils/web/2-fa b/utils/web/2-fa
--- a/utils/web/2-fa
+++ b/utils/web/2-fa
@@ -13,17 +13,15 @@ help() {
 cat <<help
 DESCRIPTION
 
-    A script that handles the details of decrypting and extracting tokens from 
-    PGP encrypted 2-FA messages. 2-FA messages must be from known sources that
-    have configuration entries in this script's config file. The default location
-    of the aforementioned config file is "${HOME}/.config/2-fa", and is a CSV of 
-    the form:
+    A script that handles the details of decrypting and extracting tokens from PGP encrypted 2-FA messages. 2-FA messages must be from known sources wit2h configuration 
+    entries in this script's config file. The default location of the aforementioned config file is "${HOME}/.config/2-fa", and is a CSV of the form:
 
-        2-FA source key,2-FA token prefix 
+        2-FA source key,2-FA extraction type,2-FA token identifier
 
-    The 2-FA token prefix is a unique character sequence in the 2-FA message that 
-    directly precedes the token. This prefix is used w/ grep to extract the token
-    from the decrypted message.
+    2-FA extraction types specifiy how tokens are extracted from messages. Valid extraction types are:
+
+        * line - extract a line "n" from 2-FA messages, where the 2-FA token identifier is "n"
+        * pattern - extract the first line that contains "pattern", where the 2-FA token identifier is "pattern" (pattern is removed from the matching line)
 
     The 2-FA message to be decrypted can read via -m|--message or the clipboard.
 
@@ -53,17 +51,15 @@ MSG_PATH=""
 
 MSG_CONTENT=""
 TWO_FA_SRC=""
-TOKEN_PREFIX=""
+TOKEN_IDENTIFIER=""
 
-
-get-2fa-token-prefix() {
-    echo "$(grep "^${TWO_FA_SRC}," ${CONFIG_PATH} | cut -d , -f2)"
+__get_extraction_type() {
+    grep "^${TWO_FA_SRC}," "${CONFIG_PATH}" | awk -F "," '{print $2}' || true
 }
 
-get-2fa-token() {
-    echo "$(echo "${MSG_CONTENT}" | gpg -d | grep "${TOKEN_PREFIX}" | cut -d ':' -f2 | xargs)"
+__get_token_identifier() {
+    grep "^${TWO_FA_SRC}," "${CONFIG_PATH}" | awk -F "," '{print $3}' || true 
 }
-
 
 while [[ $# -gt 0 ]]; do
   case $1 in
@@ -105,19 +101,37 @@ MSG_CONTENT="$([[ -n "${MSG_PATH}" && -s "${MSG_PATH}" ]] && cat "${MSG_PATH}" |
 
 if [[ -z "${MSG_CONTENT}" ]]; then
     SRC_MOD="$([[ -n "${MSG_PATH}" ]] && echo "${MSG_PATH} doesn't exist/is empty and " || echo "")"
-    echo "No 2-FA message to decrypt: ${SRC_MOD}your clipboard is empty"
+    echo "[ERROR] no 2-FA message to decrypt: ${SRC_MOD}your clipboard is empty"
     exit 1
 fi
 
-TOKEN_PREFIX="$(get-2fa-token-prefix)"
+TOKEN_EXTRACTION_TYPE="$(__get_extraction_type)"
 
-if [[ -z "${TOKEN_PREFIX}" ]]; then
-    echo "Unable to find 2-FA token prefix for \"${TWO_FA_SRC}\" in \"${CONFIG_PATH}\""
+if [[ -z "${TOKEN_EXTRACTION_TYPE}" ]]; then
+    echo "[ERROR] unable to find 2-FA token extraction type for \"${TWO_FA_SRC}\" in \"${CONFIG_PATH}\""
     exit 1
 fi
 
-TOKEN="$(get-2fa-token)"
+TOKEN_IDENTIFIER="$(__get_token_identifier)"
 
-[[ "${VERBOSE}" == "true" ]] && echo "${TOKEN}"
+if [[ -z "${TOKEN_IDENTIFIER}" ]]; then
+    echo "[ERROR] unable to find 2-FA token identifier for \"${TWO_FA_SRC}\" in \"${CONFIG_PATH}\""
+    exit 1
+fi
+
+TOKEN=""
+
+[[ "${VERBOSE}" == "true" ]] && echo "[INFO] 2-FA extraction type=${TOKEN_EXTRACTION_TYPE}, token identifier=${TOKEN_IDENTIFIER}"
+
+if [[ "${TOKEN_EXTRACTION_TYPE}" == "line" ]]; then
+    TOKEN="$(echo "${MSG_CONTENT}" | gpg -d | sed "${TOKEN_IDENTIFIER}q;d")"
+elif [[ "${TOKEN_EXTRACTION_TYPE}" == "pattern" ]]; then
+    TOKEN="$("${MSG_CONTENT}" | gpg -d | grep "${TOKEN_IDENTIFIER}" | sed "s/${TOKEN_IDENTIFIER}//" | xargs)"
+else
+    echo "[ERROR] unrecognized 2-FA token extraction type: ${TOKEN_EXTRACTION_TYPE}"
+    exit 1
+fi
+
+[[ "${VERBOSE}" == "true" ]] && echo "[INFO] token='${TOKEN}'"
 echo "${TOKEN}" | xsel --clipboard
 
