[Enhance] Add log-config Utility
* Add ulogger extension script for reading user specified ulogger toml
  config files
* Update log-level and ulogger to use the aforementioned script
* Add default ulogger config

diff --git a/log/log-level b/log/log-level
--- a/log/log-level
+++ b/log/log-level
@@ -6,7 +6,7 @@ source /etc/profile.d/shared_paths.sh
 source "${CODE_ROOT}/lib/bash/utils.sh"
 
 
-USAGE="log-level LOG_LEVEL [-v]"
+USAGE="log-level LOG_LEVEL [-v] [-t type] [-c path]"
 
 usage() {
     echo "${USAGE}"
@@ -16,7 +16,7 @@ help() {
 cat <<help
 DESCRIPTION
 
-    Validates the provided level and tests its severity against the current log level to determine if a log message needs to be written to stdout. 
+    Validates the provided level and tests its severity against the current log level to determine if a log message needs to be written to stdout.
 
     Log levels indicate the severity/urgency of a log message, and determine which messages should be propagated to callers. For example, if the current log level is WARN,
     only messages w/ a log level >= WARN (i.e.: WARN, ERROR) will propagate to callers.
@@ -38,6 +38,7 @@ DESCRIPTION
         2 - the provided log level or some global log level configuration (i.e.: CURRENT_LOG_LEVEL, DEFAULT_LOG_LEVEL) is invalid
 
     Return codes (w/ -v|--validate):
+
         0 - the provided log level is valid
         1 - the provided log level is not valid
 
@@ -52,6 +53,8 @@ POSITIONAL ARGUMENTS
 OPTIONS
 
     -v, --validate      optional; if specified, exit after validating the provided log level
+    -t, --type          optional; the active logger type, which affects log levels and files; can also be specified via $\ULOGGER_TYPE
+    -c, --config        optional; a path to a file from which to read user ulogger config
     -h, --help          optional; display this message
 help
 }
@@ -59,6 +62,7 @@ help
 
 LOG_LEVEL=""
 VALIDATE=""
+CONFIG_PATH=""
 ERROR_RC=2
 
 while [[ $# -gt 0 ]]; do
@@ -66,6 +70,16 @@ while [[ $# -gt 0 ]]; do
     -v|--validate)
       VALIDATE="true"
       ERROR_RC=1
+      shift
+      ;;
+    -t|--type)
+      export ULOGGER_TYPE="${2}"
+      shift
+      shift
+      ;;
+    -c|--config)
+      CONFIG_PATH="${2}"
+      shift
       shift
       ;;
     -h|--help)
@@ -90,31 +104,29 @@ declare -A PUBLIC_LOG_LEVELS=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4)
 # arg validation
 
 if [[ -z "${LOG_LEVEL}" ]]; then
-    echo "[ERROR] -l|--log-level is required"
+    echo "[ERROR] log level is a required positional parametr"
     exit $ERROR_RC
 fi
 
 if [[ -z "${PUBLIC_LOG_LEVELS[${LOG_LEVEL}]+x}" ]]; then
-    echo "[ERROR] -l|--log-level (${LOG_LEVEL}) is not a valid log level"
+    echo "[ERROR] '${LOG_LEVEL}' is not a valid log level"
     exit $ERROR_RC
 fi
 
 # if -v|--validate is specified, exit after validating the provided log level
-if [[ "${VALIDATE}" == "true" ]]; then
-    exit 0
-fi
+[[ "${VALIDATE}" == "true" ]] && exit 0
 
 # config validation
 
-if [[ -z "${CURRENT_LOG_LEVEL+x}" ]] && [[ -z "${DEFAULT_LOG_LEVEL+x}" ]]; then
-    echo '[ERROR] unable to determine current log level'
+CURRENT_LOG_LEVEL="$(log-config -f level -c "${CONFIG_PATH}")"
+
+if [[ -z "${CURRENT_LOG_LEVEL}" ]]; then
+    echo "[ERROR] unable to determine current log level"
     exit $ERROR_RC
-elif [[ -z "${CURRENT_LOG_LEVEL+x}" ]]; then
-    CURRENT_LOG_LEVEL="${DEFAULT_LOG_LEVEL}"
 fi
 
 if [[ -z "${LOG_LEVELS[${CURRENT_LOG_LEVEL}]+x}" ]]; then
-    echo "[ERROR] CURRENT_LOG_LEVEL (${CURRENT_LOG_LEVEL}) is not a valid log level"
+    echo "[ERROR] current log level (${CURRENT_LOG_LEVEL}) is not a valid log level"
     exit $ERROR_RC
 fi
 
@@ -122,9 +134,5 @@ CURRENT_SEVERITY="${LOG_LEVELS[${CURRENT_LOG_LEVEL}]}"
 SEVERITY="${LOG_LEVELS[${LOG_LEVEL}]}"
 
 # check if the provided level is high enough severity to log to stdout
-if [[ "${SEVERITY}" -ge "${CURRENT_SEVERITY}" ]]; then
-    exit 0
-else
-    exit 1
-fi
+[[ ${SEVERITY} -ge ${CURRENT_SEVERITY} ]] && exit 0 || exit 1
 
