[Enhance] Add Fine-Grained ulogger Verbosity Controls
* Update log-level to use environmental "log transforms", to enable
  fine-grained verbosity controls
* Add ulogger util, log-env, for viewing/updating ulogger environment
  variable
* Fix log-write handling of the "-n|--no-fmt" for lines written to
  stdout
* Fix/update ulogger interface
* Add real log-explore impl
* Update log-config to retrieve "pager" config fields
* Fix path to default config in log-config
* Add pager defaults to default ulogger config
* Update tmux-resize-layout to use new log-env utility for processing
  verbosity script flags
* Minor refactor to tmux-resize-layout logging
* Update bash arg validation utils to optionally bypass ulogger for
  error message logging
* Add new bash arg validation util functions
* Add bash "num" utils

diff --git a/tools/log/core/cmd/log-level b/tools/log/core/cmd/log-level
--- a/tools/log/core/cmd/log-level
+++ b/tools/log/core/cmd/log-level
@@ -2,7 +2,10 @@
 
 set -Eeuo pipefail
 
-[[ -s /etc/profile.d/shared_paths.sh ]] && source /etc/profile.d/shared_paths.sh
+source "${BASH_TOOLS}/lib/args/check.sh"
+source "${BASH_TOOLS}/lib/args/validate.sh" && export VALIDATE_USE_ULOGGER=""
+source "${BASH_TOOLS}/lib/num.sh"
+source "${BASH_TOOLS}/lib/utils.sh"
 
 
 USAGE="log-level LOG_LEVEL [-v] [-t type] [-c path]"
@@ -15,12 +18,17 @@ help() {
 cat <<help
 DESCRIPTION
 
-    Validates the provided level and tests its severity against the current log level to determine if a log message needs to be written to stdout.
+    Provides the following functions:
+
+        * -v|--validate validates the provided level and tests its severity against the current log level to determine if a log message needs to be written to stdout
+        * --convert converts the provided log level (or the current level, if none is provided) to a numeric severity, or vice versa if a numeric severity is provided
+        * -[{-}|1-5]|+[{+}|1-5] converts the provided log level (or the current level, if none is provided) to the level that is n level more (if "+" is used) or less
+          (if "-" is used) severe
 
     Log levels indicate the severity/urgency of a log message, and determine which messages should be propagated to callers. For example, if the current log level is WARN,
     only messages w/ a log level >= WARN (i.e.: WARN, ERROR) will propagate to callers.
 
-    Valid log levels include (in order from least to most sever):
+    Valid log levels include (in order from least to most severe):
 
         * TRACE
         * DEBUG
@@ -47,70 +55,111 @@ USAGE
 
 POSITIONAL ARGUMENTS
 
-    LOG_LEVEL           the log level to validate and test against the current log level
+    LOG_LEVEL/SEVERITY          the log level to validate and test against the current log level
 
 OPTIONS
 
-    -v, --validate      optional; if specified, exit after validating the provided log level
-    -t, --type          optional; the active logger type, which affects log levels and files; can also be specified via $\ULOGGER_TYPE
-    -c, --config        optional; a path to a file from which to read user ulogger config
-    -h, --help          optional; display this message
+    -v, --validate              optional; if specified, exit after validating the provided log level
+    -t, --type                  optional; the active logger type, which affects log levels and files; can also be specified via $\ULOGGER_TYPE
+    --convert                   optional; if specified, converts the provided log level -> numeric severity, or severity -> log level
+    -c, --config                optional; a path to a file from which to read user ulogger config
+    +*, +[1-5]                  optional; if specified, uses for comparisons the log level that is n levels more severe than the provided level (or the current level, if none is
+                                provided), where n is the # of "+" characters or the number after a single "+" character
+    -*, -[1-5]                  optional; if specified, uses for comparisons the log level that is n levels less severe than the provided level (or the current level, if none is
+                                provided), where n is the # of "-" characters or the number after a single "-" character
+    -h, --help                  optional; display this message
 help
 }
 
 
+declare -A SEVERITIES=([0]=TRACE [1]=DEBUG [2]=INFO [3]=WARN [4]=ERROR [5]=OFF)
+declare -A LOG_LEVELS=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4 [OFF]=5)
+declare -A PUBLIC_LOG_LEVELS=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4)
+
 LOG_LEVEL=""
 VALIDATE=""
+XFM=""
 CONFIG_PATH=""
 ERROR_RC=2
 
+function __to_severity() {
+    local -r level="$(to_upper "${1}")"
+    is_one_of "${level}" "${!PUBLIC_LOG_LEVELS[@]}" || return 1
+
+    local severity="${PUBLIC_LOG_LEVELS[${level}]}"
+
+    [[ -z "${severity}" ]] && return 1
+    echo "${severity}"
+}
+
+function __to_level() {
+    local severity="${1}"
+    is_one_of "${severity}" "${!SEVERITIES[@]}" || return 1
+
+    local level="${SEVERITIES[${severity}]}"
+
+    [[ -z "${level}" ]] && return 1
+    echo "${level}"
+}
+
+function __convert() {
+    local -r to_convert="$(to_upper "${1}")"
+
+    if is_one_of "${to_convert}" "${!PUBLIC_LOG_LEVELS[@]}"; then
+        __to_severity "${to_convert}" || return 1
+    elif is_one_of "${to_convert}" "${!SEVERITIES[@]}"; then
+        __to_level "${to_convert}" || return 1
+    else
+        echo "[ERROR] unrecognized log level/severity: ${to_convert}"
+        return 1
+    fi
+}
+
+function __current_level() {
+    to_upper "$(log-config -f level -c "${CONFIG_PATH}")"
+}
+
+function __extract_xfm() {
+    local xfm="${1}"
+
+    if [[ "${xfm}" =~ ^(([\+\-])([\+\-]){0,4})$ ]]; then
+        XFM="${BASH_REMATCH[2]}${#xfm}"
+    elif [[ "${xfm}" =~ ^(([\+\-])([1-5])+)$ ]]; then
+        XFM="${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
+    else
+        echo "[ERROR] invalid log level transform: (${xfm})"
+        return 1
+    fi
+}
+
+function __process_xfm() {
+    local -r current="$(__to_severity "${LOG_LEVEL}")"
+    local xfmed="$(($current"${XFM}"))"
+    local -r level="$(num::bounded $xfmed 0 5)"
+
+    LOG_LEVEL="$(__to_level "${level}")" || return 1
+}
+
 while [[ $# -gt 0 ]]; do
   case $1 in
-    -v|--validate)
-      VALIDATE="true"
-      ERROR_RC=1
-      shift
-      ;;
-    -t|--type)
-      export ULOGGER_TYPE="${2}"
-      shift
-      shift
-      ;;
-    -c|--config)
-      CONFIG_PATH="${2}"
-      shift
-      shift
-      ;;
-    -h|--help)
-      help
-      exit 0
-      ;;
-    -*)
-      usage
-      exit 1
-      ;;
-    *)
-        LOG_LEVEL="$(echo "${1}" | tr '[:lower:]' '[:upper:]')"
-      shift
-      ;;
+    -v|--validate) VALIDATE="true" ; ERROR_RC=1 ; shift ;;
+    -t|--type) export ULOGGER_TYPE="${2}" ; shift ; shift ;;
+    --convert) __convert "${2}" && exit 0 || exit 1 ;;
+    -c|--config) CONFIG_PATH="${2}" ; shift ; shift ;;
+    -h|--help) help ; exit 0 ;;
+    +*) __extract_xfm "${1}" || exit 1 ; shift ;;
+    -*) __extract_xfm "${1}" || exit 1 ; shift ;;
+    *) LOG_LEVEL="$(to_upper "${1}")" ; shift ;;
   esac
 done
 
 
-declare -A LOG_LEVELS=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4 [OFF]=5)
-declare -A PUBLIC_LOG_LEVELS=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4)
+[[ -n "${ULOGGER_LEVEL_XFM+x}" ]] && XFM="${ULOGGER_LEVEL_XFM}"
 
 # arg validation
 
-if [[ -z "${LOG_LEVEL}" ]]; then
-    echo "[ERROR] log level is a required positional parametr"
-    exit $ERROR_RC
-fi
-
-if [[ -z "${PUBLIC_LOG_LEVELS[${LOG_LEVEL}]+x}" ]]; then
-    echo "[ERROR] '${LOG_LEVEL}' is not a valid log level"
-    exit $ERROR_RC
-fi
+validate_required_positional "log level" "${LOG_LEVEL}" || exit $ERROR_RC
+validate_one_of "log level" "${LOG_LEVEL}" "${!PUBLIC_LOG_LEVELS[@]}" || exit $ERROR_RC
 
 # if -v|--validate is specified, exit after validating the provided log level
 [[ "${VALIDATE}" == "true" ]] && exit 0
@@ -118,20 +167,15 @@ fi
 # config validation
 
 CURRENT_LOG_LEVEL="$(log-config -f level -c "${CONFIG_PATH}")"
+validate_required "" "${CURRENT_LOG_LEVEL}" "unable to determine current log level" || exit $ERROR_RC
+validate_one_of "current log level" "${CURRENT_LOG_LEVEL}" "${!LOG_LEVELS[@]}" || exit $ERROR_RC
 
-if [[ -z "${CURRENT_LOG_LEVEL}" ]]; then
-    echo "[ERROR] unable to determine current log level"
-    exit $ERROR_RC
-fi
-
-if [[ -z "${LOG_LEVELS[${CURRENT_LOG_LEVEL}]+x}" ]]; then
-    echo "[ERROR] current log level (${CURRENT_LOG_LEVEL}) is not a valid log level"
-    exit $ERROR_RC
-fi
-
-CURRENT_SEVERITY="${LOG_LEVELS[${CURRENT_LOG_LEVEL}]}"
-SEVERITY="${LOG_LEVELS[${LOG_LEVEL}]}"
+# transform provided level before comparison, if necessary
+[[ -n "${XFM}" ]] && __process_xfm
 
 # check if the provided level is high enough severity to log to stdout
+CURRENT_SEVERITY="$(__to_severity "${CURRENT_LOG_LEVEL}")"
+SEVERITY="$(__to_severity "${LOG_LEVEL}")"
+
 [[ ${SEVERITY} -ge ${CURRENT_SEVERITY} ]] && exit 0 || exit 1
 
