[WIP] Add Repo Installation Script
* Add primary install script entry point, as well as os specific entry
  points
* Add cron install script
* Add systemd install script
* Move (single) cron runnable into its own sub directory
* Add file extension to systemd unit install scripts

diff --git a/system/cron/util/cronctl b/system/cron/util/cronctl
--- a/system/cron/util/cronctl
+++ b/system/cron/util/cronctl
@@ -6,7 +6,7 @@ source /etc/profile.d/shared_paths.sh
 source "${CODE_ROOT}/lib/bash/utils.sh"
 
 
-USAGE="usage: cronctl -s -c [-u] [-q] [-d] [-l path] [-m|--strict] [-v]"
+USAGE="usage: cronctl -s -c [-u] [-q] [-d] [-m|--strict] [--load|--save path] [-v]"
 
 usage() {
     echo "${USAGE}"
@@ -19,13 +19,13 @@ DESCRIPTION
 
     Modifies or queries an arbitrary user's crontab. The script has the following behavioral modifiers:
 
-    * Add (+a) - the default behavior; if no crontab entry is found w/ matching schedule and command, write it, otherwise exit w/ rc = 0 
+    * Add (+a) - the default behavior; if no crontab entry is found w/ matching schedule and command, write it, otherwise exit w/ rc = 0
     * Delete (+d,-a) - if a crontab entry is found w/ matching schedule/command, delete it, otherwise exit w/ rc = 0
     * Modify + Add (+m,+a) - if crontab entries are found w/ only a matching command, modify the existing partial matches
     * Modify + Delete; if crontab entries are found w/ only a matching command, delete the existing partial matches
-    * Query (-a,-d,-m) - query for existing matches; rc = 0 means an exact match was found, rc 1 indicates no matches were found; rc = 2 indicates one or more partial 
+    * Query (-a,-d,-m) - query for existing matches; rc = 0 means an exact match was found, rc 1 indicates no matches were found; rc = 2 indicates one or more partial
       matches were found; if specified, all CUD modifiers (+a,+d,+m) are ignored in query mode
-    * Strict (+s) - disallows modifications of partial matches and causes the script to exit w/ non-zero return codes if there are no modifications to be made to the 
+    * Strict (+s) - disallows modifications of partial matches and causes the script to exit w/ non-zero return codes if there are no modifications to be made to the
       crontab based on a call's args; rc = 1 indicates that a crontab addition or deletion was requested, but that the entry already exists or doesn't exist, respectively;
       rc = 2 indicates a partial match was found and no action can be taken
 
@@ -38,12 +38,13 @@ OPTIONS
     -s, --schedule      the cron schedule string
     -c, --cmd           the cmd to run
     -u, --user          optional; defaults to the current user; the user whose crontab should be written/queried
-    -q, --query         optional; if present, the script will query for a matching crontab entry; return code 0 indicates the entry is already present, return code 1 
+    -q, --query         optional; if present, the script will query for a matching crontab entry; return code 0 indicates the entry is already present, return code 1
                         indicates it's not, and return code 2 indicates that an entry w/ the provided command is present, but the entry's schedule is different
-    -l, --log           optional, should be a valid file path; ignored for deletions (-d|--delete); if present, a cron's stdout output will be redirected to this file
     -m, --modify        optional; mutually exclusive w/ --strict; if present, the script will modify an entry's schedule if an entry w/ a matching cmd is found
     -d, --delete        optional; if present, the script will delete an entry if a full match found, and will delete an entry if a cmd match is found and -m is specified
-    --strict            optional; mutually exclusive w/ -m; if present, instead of ignoring or updating a matching entry, the script will fail w/ a return code of 1 if an 
+    --load              optional; a path from which to load the crontab for -u|--user
+    --save              optional; a path to which to save the crontab for -u|--user
+    --strict            optional; mutually exclusive w/ -m; if present, instead of ignoring or updating a matching entry, the script will fail w/ a return code of 1 if an
                         existing entry matches entirely, or 2 if an entry's cmd matches
     -v, --verbose       optional; if present, the script will print to stdout messages about the script's progress
     -h, --help          display this message
@@ -55,7 +56,6 @@ SCHEDULE=""
 CMD=""
 FOR_USER="${USERNAME}"
 QUERY=""
-LOG_PATH=""
 MODIFY=""
 DELETE=""
 STRICT=""
@@ -77,7 +77,7 @@ while [[ $# -gt 0 ]]; do
       shift
       ;;
     -c|--cmd)
-      CMD="$([[ -z "${2+x}" ]] && echo "" || echo "${2}")"      
+      CMD="$([[ -z "${2+x}" ]] && echo "" || echo "${2}")"
       shift
       shift
       ;;
@@ -88,11 +88,6 @@ while [[ $# -gt 0 ]]; do
       ;;
     -q|--query)
       QUERY="true"
-      shift
-      ;;
-    -l|--log)
-      LOG_PATH="$([[ -z "${2+x}" ]] && echo "" || echo "${2}")"      
-      shift
       shift
       ;;
     -m|--modify)
@@ -229,7 +224,7 @@ handle_nothing_to_do() {
 }
 
 
-# arg validation 
+# arg validation
 
 if [[ -z "${SCHEDULE}" && "${QUERY}" != "true" ]]; then
     log "-s|--schedule is required" "ERROR" "true" "true"
@@ -238,11 +233,6 @@ fi
 
 if [[ -z "${CMD}" && "${QUERY}" != "true" ]]; then
     log "-c|--cmd is required" "ERROR" "true" "true"
-    exit 1
-fi
-
-if [[ -n "${LOG_PATH}" && ! -f "${LOG_PATH}" ]]; then
-    log "-l|--log must be a valid file path" "ERROR" "true" "true"
     exit 1
 fi
 
@@ -258,8 +248,7 @@ fi
 set_modes
 log "Running w/ modifiers=$(get_modes_str)" "INFO" "false" "true"
 
-LOG_STR="$([[ -n "${LOG_PATH}" ]] && echo " >> ${LOG_PATH}" || echo "")"
-CRONTAB_LINE="$(echo "${SCHEDULE} ${CMD}${LOG_STR}" | xargs)"
+CRONTAB_LINE="$(echo "${SCHEDULE} ${CMD}" | xargs)"
 
 if [[ -n "${CRONTAB_LINE}" ]]; then
     log "Using crontab line \"${CRONTAB_LINE}\""
@@ -268,7 +257,7 @@ else
 fi
 
 log "Reading crontab content"
-[[ "${FOR_USER}" != "${USER}" ]] && log "-u|--user != ${USER}; credential check required >>>" 
+[[ "${FOR_USER}" != "${USER}" ]] && log "-u|--user != ${USER}; credential check required >>>"
 
 CRONTAB_CONTENT="$([[ "${FOR_USER}" == "root" ]] && sudo crontab -u "${FOR_USER}" -l || crontab -u "${FOR_USER}" -l)"
 
