[Refactor] Update Tmux Scripts
* Add tmux api util functions
* Update tmux scripts to conform to updated standards and to use new
  util functions

diff --git a/tools/tmux/tmux-resize-layout b/tools/tmux/tmux-resize-layout
--- a/tools/tmux/tmux-resize-layout
+++ b/tools/tmux/tmux-resize-layout
@@ -2,12 +2,12 @@
 
 set -Eeuo pipefail
 
-source /etc/profile.d/shared_paths.sh
+source "${BASH_LIB}/args/validate.sh"
 source "${BASH_LIB}/core/str.sh"
 source "${BASH_LIB}/log/utils.sh"
 
 
-USAGE="tmux-resize-layout [-l layout] [-t window] [-s path] [--strict] [--force]"
+USAGE="tmux-resize-layout [-l layout] [-t window] [-s path] {flags}"
 
 usage() {
     echo "usage: ${USAGE}"
@@ -54,11 +54,13 @@ OPTIONS
     -l, --layout        optional; if not provided, will pull value from window name if in the format  ".* \(layout-type\)"; the layout to use
     -t, --target        optional, defaults to the active window; the name of the window for which to set a layout
     -s, --specs         optional, default to "\${XDG_CONFIG_HOME}/tmux/layouts"; a file that contains layout specifications in the format describe about
-    --strict            optional; can't be used w/ --dry-run; if specified, error cases will case the script to exit with non-zero return codes; see above for specific
+
+FLAGS
+
+    --strict            can't be used w/ --dry-run; if specified, error cases will case the script to exit with non-zero return codes; see above for specific
                         behavioral description
-    --force             optional; if specified, forces resize even if pane dimensions match those in the layout spec
-    -v, --verbose       optional; write progress/status messages to stdout
-    --dry-run           optional; can't be used w/ --force; indicates that the script should print hypothetical results to the console, but make no state changes
+    --force             if specified, forces resize even if pane dimensions match those in the layout spec
+    --dry-run           can't be used w/ --force; indicates that the script should print hypothetical results to the console, but make no state changes
     -h, --help          display this message
 help
 }
@@ -78,7 +80,7 @@ log() {
     ulogger info "${1}" || echo -n ""
 }
 
-__log_and_exit() {
+log_and_exit() {
     local msg="${1}"; shift
 
     if [[ "${STRICT}" == "true" ]]; then
@@ -90,24 +92,24 @@ __log_and_exit() {
     fi
 }
 
-__log_or_exit() {
+log_or_exit() {
     local msg="${1}" ; shift
 
     if [[ -n "${STRICT}" ]]; then
-        __log_and_exit "${msg}" "$@"
+        log_and_exit "${msg}" "$@"
     else
         ulogger warn "${msg}" "$@"
     fi
 }
 
-__extract_layout_from_name() {
+extract_layout_from_name() {
     # FIXME: the pattern used to extract the layout-type from window name should not allow whitespace
     #        characters, and should probably be restricted to alphanumeric and hyphens + underscores;
     #        I couldn't for the life of me get that pattern to work
     [[ "${TARGET}" =~ .*[[:space:]]\((.*)\)$ ]] && echo "${BASH_REMATCH[1]}" || echo ""
 }
 
-__extract_layout_from_env() {
+extract_layout_from_env() {
     local -r env_var="TMUX_$(str::upper "${TARGET}_LAYOUT")"
     local -r env_val="$(tmux show-environment "${env_var}" 2> /dev/null || echo "")"
 
@@ -119,50 +121,32 @@ LogFlags::process_log_flags "$@"
 while [[ $# -gt 0 ]]; do
   case $1 in
     -l|--layout)
-      LAYOUT="$([[ -z "${2+x}" ]] && echo "" || echo "${2}")"
-      shift
-      shift
-      ;;
+      [[ -n "${2:-}" ]] && LAYOUT="${2}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
     -t|--target)
-      TARGET="$([[ -z "${2+x}" ]] && echo "${TARGET}" || echo "${2}")"
-      shift
-      shift
-      ;;
+      [[ -n "${2:-}" ]] && TARGET="${2}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
     -s|--specs)
-      SPEC_PATH="$([[ -z "${2+x}" ]] && echo "${SPEC_PATH}" || echo "${2}")"
-      shift
-      shift
-      ;;
+      [[ -n "${2:-}" ]] && SPEC_PATH="${2}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
     --strict)
-      STRICT="true"
-      shift
-      ;;
-    --dry-run)
-      DRY_RUN="true"
-      shift
-      ;;
-    -h|--help)
-      help
-      exit 0
-      ;;
+      STRICT="true" ; shift ;;
+    --force)
+      FORCE="true" ; shift ;;
     -v*|-q*)
       shift ;;
+    --dry-run)
+      DRY_RUN="true" ; shift ;;
+    -h|--help)
+      help && exit 0 ;;
     *)
-      usage
-      exit 1
-      ;;
+      ulogger error "$(usage)" && exit 1 ;;
   esac
 done
 
 
-if [[ "${DRY_RUN}" == "true" && "${FORCE}" == "true" ]]; then
-    echo "--force and --dry-run are mutually exclusive"
-    exit 1
-fi
+validate_mutually_exclusive "${DRY_RUN}" "--dry-run" "${FORCE}" "--force" || exit 1
 
 # validate target refers to a window
 if [[ -z "$(tmux list-windows -F "#W" | grep "${TARGET}" || true)" ]]; then
-    __log_and_exit "tmux window target='${TARGET}' does not exist"
+    log_and_exit "tmux window target='${TARGET}' does not exist"
 fi
 
 # get window id
@@ -176,26 +160,23 @@ if [[ "${MATCHING_TARGETS}" != "${TARGET_ID}" ]]; then
     TARGET_IDS="${TARGET_IDS:0:-1}"
     MSG="multiple windows found for target='${TARGET}' (ids: ${TARGET_IDS})"
     # exit only if using strict mode (that's why we're not just using log_and_exit here)
-    __log_or_exit "${MSG}"
+    log_or_exit "${MSG}"
 fi
 
 ulogger info "preparing to set layout for target window='${TARGET}' (id: ${TARGET_ID})"
 
 # if layout-type isn't provided, try to extract it from window name
-[[ -z "${LAYOUT}" ]] && LAYOUT="$(__extract_layout_from_name)"
+[[ -z "${LAYOUT}" ]] && LAYOUT="$(extract_layout_from_name)"
 
 if [[ -n "${LAYOUT}" ]]; then
     ulogger info "no layout provided; extracted layout='${LAYOUT}' from window name='${TARGET}'"
 else
-    LAYOUT="$(__extract_layout_from_env)"
+    LAYOUT="$(extract_layout_from_env)"
     [[ -n "${LAYOUT}" ]] && ulogger info "no layout provided; extracted layout='${LAYOUT}' from tmux env"
 fi
 
 [[ -z "${LAYOUT}" ]] && ulogger info "no layout provided; unable to extract layout"
-
-if [[ ! -f "${SPEC_PATH}" ]]; then
-    __log_and_exit "spec file='${SPEC_PATH}' does not exist"
-fi
+validate_file "${SPEC_PATH}" "-s|--specs" || exit 1
 
 # build layout identifier from window dimensions, pane count, and, optionally, the identifier
 DIMENSIONS="$(tmux display-message -t "${TARGET_ID}" -p "#{window_width}x#{window_height}")"
@@ -209,7 +190,7 @@ ulogger info "searching for layout specification with identifier='${IDENTIFIER}'
 # filter out comments before grepping for identifier
 readarray -t SPEC_MATCHES < <(grep -v "^#" "${SPEC_PATH}" | grep "${IDENTIFIER}")
 if [[ "${#SPEC_MATCHES[@]}" -eq 0 ]]; then
-    __log_and_exit "no layout specification found for '${IDENTIFIER}'"
+    log_and_exit "no layout specification found for '${IDENTIFIER}'"
 fi
 
 ulogger info "found spec match(es):"
@@ -220,7 +201,7 @@ done
 # ensure that we have only one match for the current identifier; if the original match is
 # different from this "single match", we know we originally found > 1 match
 if [[ "${#SPEC_MATCHES[@]}" -gt 1 ]]; then
-    __log_or_exit "multiple layout specifications found for '${IDENTIFIER}'"
+    log_or_exit "multiple layout specifications found for '${IDENTIFIER}'"
 fi
 
 SPEC_MATCH="${SPEC_MATCHES[0]}"
@@ -229,7 +210,7 @@ ulogger info "extracting layout specification from match='${SPEC_MATCH}'"
 # extract get the tmux layout from the spec
 LAYOUT_SPEC="$(echo "${SPEC_MATCH}" | cut -d " " -f4)"
 if [[ -z "${LAYOUT_SPEC}" ]]; then
-    __log_and_exit "unable to extract layout specification from spec match='${SPEC_MATCH}'"
+    log_and_exit "unable to extract layout specification from spec match='${SPEC_MATCH}'"
 fi
 
 ulogger info "using extracted layout specification='${LAYOUT_SPEC}'"
diff --git a/tools/tmux/tmux-shift-window b/tools/tmux/tmux-shift-window
--- a/tools/tmux/tmux-shift-window
+++ b/tools/tmux/tmux-shift-window
@@ -2,8 +2,12 @@
 
 set -Eeuo pipefail
 
+source "${BASH_LIB}/api/tmux.sh"
+source "${BASH_LIB}/args/validate.sh"
+source "${BASH_LIB}/log/utils.sh"
 
-USAGE="tmux-shift-window -d l[eft]|r[ight] [-n num]"
+
+USAGE="tmux-shift-window -d l[eft]|r[ight] [-n num] {flags}"
 
 usage() {
     echo "usage: ${USAGE}"
@@ -23,6 +27,9 @@ OPTIONS
 
     -d, --direction     l[eft] or r[ight]; the direction in which to shift the window
     -n, --num           optional, defaults to 1; integer; the number of places to shift the window
+
+FLAGS
+
     -h, --help          display this message
 help
 }
@@ -31,44 +38,36 @@ help
 DIRECTION=""
 NUM="1"
 
+LogFlags::process_log_flags "$@"
+
 while [[ $# -gt 0 ]]; do
   case $1 in
     -d|--direction)
-      DIRECTION="$([[ -z "${2+x}" ]] && echo "" || echo "${2}")"
-      shift
-      shift
-      ;;
+      [[ -n "${2:-}" ]] && DIRECTION="${2:-}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
     -n|--num)
-      NUM="${2}"
-      shift
-      shift
-      ;;
+      [[ -n "${2:-}" ]] && NUM="${2:-}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
+    -v*|-q*)
+      shift ;;
     -h|--help)
-      help
-      exit 0
-      ;;
+      help && exit 0 ;;
     *)
-      usage
-      exit 1
-      ;;
+      ulogger error "$(usage)" && exit 1 ;;
   esac
 done
 
 
-if [[ -z "${DIRECTION}" ]]; then
-    ulogger error "-d|--direction is a required parameter"
-    exit 1
-fi
-
-if [[ "${DIRECTION}" != +(l|left|r|right) ]]; then
-    ulogger error "-d|--direction must be one of l[eft]|r[ight]"
-    exit 1
-fi
+validate_required "-d|--direction" "${DIRECTION}" || exit 1
+validate_one_of "-d|--direction" "${DIRECTION}" "l" "left" "r" "right" || exit 1
 
 SIGN="$([[ "${DIRECTION}" =~ l(eft)? ]] && echo "-" || echo "+")"
-TO_SHIFT_IDX="$(tmux display-message -p "#I")"
+TO_SHIFT_IDX="$(tmux::window_idx)"
 # shellcheck disable=SC1102
-NEW_IDX="$((${TO_SHIFT_IDX} "${SIGN}" "${NUM}"))"
+# shellcheck disable=SC2086
+NEW_IDX=$(($TO_SHIFT_IDX "${SIGN}" $NUM))
 
-tmux swap-window -d -s "${TO_SHIFT_IDX}" -t "${NEW_IDX}"
+WINDOW_NAME="$(tmux::window_name)"
+ulogger info "moving window=${WINDOW_NAME} from position $TO_SHIFT_IDX to $NEW_IDX"
+
+ERR="$(tmux swap-window -d -s "${TO_SHIFT_IDX}" -t "${NEW_IDX}" 2>&1)" || true
+if [[ -n "${ERR}" ]]; then ulogger error "${ERR}" && exit 1 ; fi
 
